services:
  cd1823:
    build: .
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - ./home/:/home
    ports:
      - "${JUPYTER_PORT:-8888}:8888"
      - "${TENSORBOARD_PORT:-6006}:6006"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${GPU_DEVICES}']
              capabilities: [gpu]
    working_dir: /home
    command: jupyter-lab --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token="${JUPYTER_TOKEN}" --NotebookApp.password='' --notebook-dir=/home

