services:
  nd892:
    build: .
    command: bash
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - /home/kwchun/Workspace/uw2/nd892/ddn-speech-recognizer/data:/data
      - /home/kwchun/Workspace/uw2/nd892/ddn-speech-recognizer/home:/home
    ports:
      - "${JUPYTER_PORT}:8888"
      - "${TENSORBOARD_PORT}:6006"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    working_dir: /home
    command: jupyter-lab --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token="${JUPYTER_TOKEN}" --NotebookApp.password='' --notebook-dir=/home

