services:
  cd0184:
    image: nvcr.io/nvidia/pytorch:24.01-py3
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - ./home:/home
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    working_dir: /home
    command: bash
    tty: true
