#ifndef COMPRESS_H
#define COMPRESS_H

/**
 * @brief Compresses the given input file using the default compression algorithm.
 *
 * This function reads the contents of the specified input file, compresses it using
 * the default compression algorithm, and writes the compressed data to a new file
 * with the same base name but with a .rle extension. If the output file already exists,
 * a unique name is generated by appending an underscore and a version number.
 *
 * @param input_file_name The name of the input file to be compressed.
 * @return int Returns 0 on success, or 1 on failure.
 */
int compress(const char *input_file_name);

#endif // COMPRESS_H