#ifndef DECOMPRESS_H
#define DECOMPRESS_H

/**
 * @file decompress.h
 * @brief Function declarations for the decompression algorithm.
 *
 * This header file contains the declaration of the decompression function
 * used in the application. The decompression function reads a compressed
 * file and writes the decompressed data to a new file.
 */

/**
 * @brief Decompresses the given input file using the default decompression algorithm.
 *
 * This function reads the contents of the specified input file, decompresses it using
 * the default decompression algorithm, and writes the decompressed data to a new file
 * with the same base name but with a .txt extension. If the output file already exists,
 * a unique name is generated by appending an underscore and a version number.
 *
 * @param input_file_name The name of the input file to be decompressed.
 * @return int Returns 0 on success, or 1 on failure.
 */
int decompress(const char *input_file_name);

#endif // DECOMPRESS_H