FROM nvcr.io/nvidia/pytorch:21.11-py3

# [Optional] Uncomment this section to install additional OS packages.
RUN apt-get update \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
        nodejs \
        npm \
    && apt-get clean autoclean \
    && apt-get autoremove --yes
#    && rm -rf /var/lib/apt/lists/*
#    && rm -rf /var/lib/{apt,dpkg,cache,log}/

RUN pip install voila==0.3.6 ipywidgets==7.5.0 nbconvert==6.4.5

RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager@2

RUN jupyter serverextension enable voila \
    && jupyter server extension enable voila
