services:
  nd089:
    build: .
    ipc: host
    volumes:
      - /home/kwchun/Workspace:/home
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    working_dir: /home
    command: jupyter-lab --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token="$JUPYTER_TOKEN" --NotebookApp.password='' --notebook-dir=/home
