services:
  cd12440:
    build: .
    volumes:
      - ./home:/home
    ports:
      - "${JUPYTER_PORT}:8888"
    working_dir: /home
    command: jupyter-lab --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token="$JUPYTER_TOKEN" --notebook-dir=/home

