services:
  cd0029:
    build: .
    volumes:
      - ./home:/home
    ports:
      - "${JUPYTER_PORT}:8888"
    working_dir: /home
    command: jupyter-lab --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token="$JUPYTER_TOKEN" --notebook-dir=/home

  postgres:
    image: arm64v8/postgres
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  cassandra:
    image: arm64v8/cassandra
    volumes:
      - ./cassandra:/var/lib/cassandra

  adminer:
    image: arm64v8/adminer

