services:
  nd0013-kr:
    build: .
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - ./home:/home
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority  
    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
    network_mode: "host"
    ports:
      - "${JUPYTER_PORT}:8888"
      - "${TENSORBOARD_PORT}:6006"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${GPU_DEVICES}']
              capabilities: [gpu]
    working_dir: /home
    command: jupyter notebook --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token="${JUPYTER_TOKEN}" --NotebookApp.password="" --notebook-dir=/home

