version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT:-8080}:8080"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      #      - "{PGADMIN_PORT:-4104}:80"
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ruddyscent@gmail.com
      PGADMIN_DEFAULT_PASSWORD: example
