services:
  ud810:
    build: .
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - ./home:/home
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    ports:
      - "${JUPYTER_PORT}:8888"
        #      - "${TENSORBOARD_PORT}:6006"
    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
        #    network_mode: "host"
    working_dir: /home
    command: jupyter-lab --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token="$JUPYTER_TOKEN" --NotebookApp.password='' --notebook-dir=/home
